### PR TITLE
solved KidNotFound error during signature verification

### PR DESCRIPTION
**Pull request by TheTesla**
This is a temporary fix. We will reintroduce signature verification without kid later.

### CODE REVIEW

**Comment by TheTesla** [comment]
The problem was only the type of the key. It was given as a set or list. In this case kid is needed to select the corresponding key. But we have only one key given and no kid defined in the jwt. So we can convert the set/list of key to one key by selecting the first and only before giving it to the function.

**Comment by gcolson** [comment]
I had the same issue and tested with the first commit a43dd23 : it didn't work better for me.
e2e529e seem to fix the issue for me but, as you say, a way to reintroduce signature verification need to be found..

**Comment by TheTesla** [comment]
> I had the same issue and tested with the first commit [a43dd23](https://github.com/m0n9oose/omniauth_openid_connect/commit/a43dd23ae8f6c5c488c2774091c54419a8b6474d) : it didn't work better for me.
> [e2e529e](https://github.com/m0n9oose/omniauth_openid_connect/commit/e2e529e68e6882be9638e89f4a77563aed0ad7e7) seem to fix the issue for me but, as you say, a way to reintroduce signature verification need to be found..

So maybe the key is missing entirely for you. Please, post the error message.

**Comment by stanhu** [comment]
I believe https://github.com/nov/json-jwt/pull/92 is the proper fix for this issue.

**Pull request closed without merging**
