### PR TITLE
Allow to update omniauth to 2

### PR DESCRIPTION
**Pull request by formigarafa**
This PR is to allow users of this gem to update omniauth to version 2 (security fix).
I have also made some adjustments to make rubocop pass.

### CODE REVIEW

**Comment by formigarafa** [comment]
I am not very knowlegeable about these github actions but they passed on my fork (https://github.com/formigarafa/omniauth_openid_connect/runs/2378846138).

If anyone could tell me if there is anything I could do to make it work, I would realle appreciate it. Thanks.

**Comment by formigarafa** [comment]
What kind of activity this bot expects?

**Comment by formigarafa** [comment]
What kind of activity this bot expects?

**Comment by andrewshadura** [comment]
I guess the bot is going to arrive some time soon again 🙂

**Pull request merged**
