### PR TITLE
Move verification of IdToken to before accessing tokens

### LINKED ISSUE #27: Nonce verification
Currently, nonce is verified in [`access_token`](https://github.com/m0n9oose/omniauth_openid_connect/blob/3913c8fd0518b929d384f27d2cf6e370dd36f853/lib/omniauth/strategies/openid_connect.rb#L204) method and it's way too late.
I think nonce should be validated after this line: https://github.com/m0n9oose/omniauth_openid_connect/blob/3913c8fd0518b929d384f27d2cf6e370dd36f853/lib/omniauth/strategies/openid_connect.rb#L112

```ruby
id_token = decode_id_token(params['id_token'])

id_token.verify!(
  issuer: options.issuer,
  client_id: client_options.identifier,
  nonce: stored_nonce
)
```

Verifying the response during requesting for a token doesn't make sense.

### PR DESCRIPTION
**Pull request by krzysiek1507**
Closes #27

### CODE REVIEW

**Comment by krzysiek1507** [comment]
@m0n9oose friendly ping ;)

**Comment by krzysiek1507** [comment]
Any chance for a new release?

**Comment by m0n9oose** [comment]
@krzysiek1507 yeah, sure. I was going to ask you to test current `master` branch one more time before i push this update to the rubygems. Can you help me with this?

**Comment by krzysiek1507** [comment]
@m0n9oose I've tested my changes on in my application already.

**Comment by krzysiek1507** [comment]
Without this change, my application throws a validation error all the time.

**Comment by m0n9oose** [comment]
> I've tested my changes on in my application already.
yeah, i know but this release has another changes and it would be great to test it properly before push to public

> Without this change, my application throws a validation error all the time.
Sorry i didn't get it. Current `master` is stable for you?

**Comment by krzysiek1507** [comment]
@m0n9oose tested `master` and it works for me.

**Comment by Eric-Guo** [comment]
@m0n9oose I testing the master, same as v0.3.2 (definitely), because it's same code...

I still can not catch the purpose of this PR (#28)

**Comment by kmeister2000** [comment]
After updating from 0.3.1 to 0.3.2 I am receiving a similar error to @Eric-Guo in a Rails 5.2 app:

```
 class << self
      def decode_compact_serialized(jwt_string, key_or_secret, algorithms = nil, encryption_methods = nil, allow_blank_payload = false)
        case jwt_string.count('.') + 1
        when JWS::NUM_OF_SEGMENTS
          JWS.decode_compact_serialized jwt_string, key_or_secret, algorithms, allow_blank_payload
        when JWE::NUM_OF_SEGMENTS
```
Backtrace
```
json-jwt (1.10.2) lib/json/jwt.rb:102:in `decode_compact_serialized'
json-jwt (1.10.2) lib/json/jose.rb:63:in `decode'
openid_connect (1.1.8) lib/openid_connect/response_object/id_token.rb:70:in `decode'
omniauth_openid_connect (0.3.2) lib/omniauth/strategies/openid_connect.rb:210:in `decode_id_token'
omniauth_openid_connect (0.3.2) lib/omniauth/strategies/openid_connect.rb:116:in `callback_phase'
omniauth (1.9.0) lib/omniauth/strategy.rb:238:in `callback_call'
omniauth (1.9.0) lib/omniauth/strategy.rb:189:in `call!'
omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.0) lib/omniauth/builder.rb:64:in `call'
rack (2.0.6) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.6) lib/rack/etag.rb:25:in `call'
rack (2.0.6) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.6) lib/rack/head.rb:12:in `call'
actionpack (5.2.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.2.1) lib/rails/rack/logger.rb:28:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
sentry-raven (2.7.4) lib/raven/integrations/rack.rb:51:in `call'
railties (5.2.2.1) lib/rails/engine.rb:524:in `call'
railties (5.2.2.1) lib/rails/railtie.rb:190:in `public_send'
railties (5.2.2.1) lib/rails/railtie.rb:190:in `method_missing'
/usr/local/rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/passenger-5.0.28/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/local/rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/passenger-5.0.28/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
/usr/local/rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/passenger-5.0.28/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/local/rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/passenger-5.0.28/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/local/rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/passenger-5.0.28/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

I'm reverting and locking to 0.3.1 until I have more time to see if I can help figure out the cause of the regression.

Also, thanks for this gem - it's been a key part of helping migrate several old Rails apps from rubycas to openid connect.

**Comment by krzysiek1507** [comment]
@Eric-Guo @kmeister2000 what is our config?

**Comment by m0n9oose** [comment]
Got it. Will take a look as soon as I can.

**Comment by krzysiek1507** [comment]
I found the problem. I have in my config `response_type: %i[id_token code]` so it worked ok, but you guys probably don't have `id_token` there.

**Comment by krzysiek1507** [comment]
I've sent PR #34. Sorry!

**Comment by stanhu** [comment]
I ran into the same problem as https://github.com/m0n9oose/omniauth_openid_connect/pull/28#issuecomment-520260446 while trying to upgrade GitLab to use v0.3.2. It looks like the work in #34 has carried over to #38. Can we help get that moving?

**Comment by m0n9oose** [comment]
@stanhu could you take a look at [this](https://github.com/m0n9oose/omniauth_openid_connect/pull/41) PR and let me know if it works for you

**Comment by stanhu** [comment]
@m0n9oose #40 seems to have worked. I also needed to ensure #36 was there in v0.3.2.

**Pull request merged**
