### PR TITLE
Try to verify id_token when response_type is code

### PR DESCRIPTION
**Pull request by naari3**
id_token verification when response_type is `code` was removed by https://github.com/m0n9oose/omniauth_openid_connect/pull/41 and https://github.com/m0n9oose/omniauth_openid_connect/pull/28
But this is a mistake according to [openid connect specs](https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse) because there must include id_token, then should do verification.

### CODE REVIEW

**Comment by naari3** [comment]
@m0n9oose Please check this one when you have time :)

**Comment by naari3** [comment]
@m0n9oose hello, Do you have any ideas?

**Comment by m0n9oose** [comment]
@naari3 thanks for contributing,

Why did you remove `test_callback_phase` test suite?

**Comment by naari3** [comment]
@m0n9oose oh sorry I missed it and I fixed one, force pushed now

**Comment by naari3** [comment]
@m0n9oose Can you check this changes? thanks !

**Pull request merged**
