### PR TITLE
Do not try to verify id_token when id_token is not used

### LINKED ISSUE #40: Issue with parsing id_token parameter in 'code' response_type use cases
First off, thanks for continuing to maintain this code!

We currently have a 'code' based implementation working with this gem. When upgrading to the latest code we're running into issues with the following lines:

https://github.com/m0n9oose/omniauth_openid_connect/blob/e05e60ddbaa4374d6375eecd441fec46232c59fe/lib/omniauth/strategies/openid_connect.rb#L121-L124

We don't have an 'id_token' param and so `decode_id_token` attempts to parse nil which causes an error. A simple conditional check of the response type before calling `decode_id_token` fixes the error.

Wanted to raise it here though in case there is something I am missing. Thanks!

### PR DESCRIPTION
**Pull request by m0n9oose**
fix #40

### CODE REVIEW

**Comment by Sutto** [comment]
+1 to this - We hit this trying to integrate a Keycloak SSO client with our app, as the default flow won't return an `id_token`, so without this it crashes with an internal exception.

**Comment by m0n9oose** [comment]
@Sutto have you tried to use branch with fix?

```
gem 'omniauth_openid_connect', git: 'https://github.com/m0n9oose/omniauth_openid_connect.git', branch: 'fix_redundant_token_verification'
```

**Comment by Sutto** [comment]
Yehp! The fix works perfectly in our case, thank you - It'd be nice to see this in a released gem version, so we don't have to depend on a git repo.

Thanks for building this btw!

**Comment by swapab** [comment]
@m0n9oose Thanks for maintaining `omniauth_openid_connect` gem.

The proposed change complies to [openid-specs](https://openid.net/specs/openid-connect-core-1_0.html) and should be merged. But, there is slight caveat which probably needs to be addressed as well.
The call [`valid_response_type?`](https://github.com/m0n9oose/omniauth_openid_connect/blob/fix_redundant_token_verification/lib/omniauth/strategies/openid_connect.rb#L117) should be removed. According to the openid-documentation and [examples](https://openid.net/specs/openid-connect-core-1_0.html#AuthorizationExamples) `response_type` is not returned in the `Location` header of the response.

Rather the validation should be in `request_phase` instead of`callback_phase`.
The RFC also says the same: https://tools.ietf.org/html/rfc6749

---
Let me know what you think about it and I can create a new pull request.

**Comment by m0n9oose** [comment]
> @m0n9oose Thanks for maintaining `omniauth_openid_connect` gem.
> 
> The proposed change complies to [openid-specs](https://openid.net/specs/openid-connect-core-1_0.html) and should be merged. But, there is slight caveat which probably needs to be addressed as well.
> The call [`valid_response_type?`](https://github.com/m0n9oose/omniauth_openid_connect/blob/fix_redundant_token_verification/lib/omniauth/strategies/openid_connect.rb#L117) should be removed. According to the openid-documentation and [examples](https://openid.net/specs/openid-connect-core-1_0.html#AuthorizationExamples) `response_type` is not returned in the `Location` header of the response.
> 
> Rather the validation should be in `request_phase` instead of`callback_phase`.
> The RFC also says the same: https://tools.ietf.org/html/rfc6749
> 
> Let me know what you think about it and I can create a new pull request.

@swapab thanks for your feedback and efforts to gather all this information, this is an excellent example of productive discussion!

I would be very appreciated if you can fork this repo and open a new pull request with additional improvements.

**Comment by m0n9oose** [comment]
@swapab any luck with implementation according to the RFC?

**Pull request merged**
