### PR TITLE
Make `omniauth_openid_connect` gem compatible with `omniauth v2.0`

### PR DESCRIPTION
**Pull request by tim-s-ccs**
As the `omniauth` is now at version > 2.0, I have updated `omniauth_openid_connect` so that it is compatible with the latest version. I also updated the other dependencies so that they use the latest versions as well.

There were two major changes I found that needed to be fixed:

1. In `omniauth` the following methods `request_path` was updated to include `script_name`, The method for `script_name` is:
```
def script_name
  @env['SCRIPT_NAME'] || ''
end
```
and it would raise an error whenever `request_path` was called as `@env` would be nil. Therefore, I added a method into `lib/omniauth/strategies/openid_connect.rb` which will return `''` if `@env` is `nil` and will use the method in `lib/omniauth/strategy.rb` as normal if `@env` is not `nil`. This is similar to what was done for `session` already.

2. There was a change in the `omniauth` gem for the `current_path` in `lib/omniauth/strategy.rb` which changed from using `path_info` to the `path` method as `path_info` has been depreciated. This did not affect the code in the library but it did impact on the tests. This is because `path_info` was being stubbed. Therefore, I changed the places in the tests where `path_info` was being stubbed to stub `path` instead.

After these changes were made, I was able to run all the test successfully.
Screenshot 2021-08-31 at 10 28 10

### CODE REVIEW

**Review by formigarafa — APPROVED** [review]

**Comment by formigarafa** [comment]
I hope this one get merged.
I have a PR open since April (#88) could not make it pass the specs on github even though they passed local.
There was another on (#84) closed because of lack of activity.

Yours at least is green, I am crossing my fingers to get this one in.

**Comment by tim-s-ccs** [comment]
> I hope this one get merged.
> I have a PR open since April (#88) could not make it pass the specs on github even though they passed local.
> There was another on (#84) closed because of lack of activity.
> 
> ~Yours at least is green~(edit: They disabled rubocop check), I am crossing my fingers to get this one in.

It's been a long time since there were any updates on this gem. I think at this point you're better off just using your own fork of it, that's what we are doing. I can't see this PR making any more progress than yours was able to I'm afraid.

**Comment by tim-s-ccs** [comment]
> What is blocking from merging this one ?

The project is not being supported anymore it seems.
This fix can be used however so you will need to target the branch.

**Comment by slevesque** [comment]
> > What is blocking from merging this one ?
> 
> The project is not being supported anymore it seems. This fix can be used however so you will need to target the branch.

Time to have a new project maintainer so ?!

**Comment by tim-s-ccs** [comment]
> Time to have a new project maintainer so ?!

It looks like someone has already done this https://github.com/m0n9oose/omniauth_openid_connect/issues/99:
https://github.com/netsphere-labs/omniauth-openid-connect/

**Comment by m0n9oose** [comment]
Sorry for this huge delay. You're right, i could use some help with maintaining this project.

Back to subject: just merged very similar PR. Could you please rebase your working branch and resolve conflicts, so i could merge some of these changes.

@tim-s-ccs if you interested in helping me with with maintaining this repo - please let me know

**Comment by tim-s-ccs** [comment]
> Sorry for this huge delay. You're right, i could use some help with maintaining this project.
> 
> Back to subject: just merged very similar PR. Could you please rebase your working branch and resolve conflicts, so i could merge some of these changes.
> 
> @tim-s-ccs & @formigarafa if you interested in helping me with with maintaining this repo - please let me know

If I had better knowledge of how it all worked I would but unfortunately I don't. My knowledge doesn't go much beyond 'what changes do I need to make this compatible with `omniauth v2.0`' 😞 . If there is anything else I can do please ask.

**Comment by tim-s-ccs** [comment]
I'm going to close this as a similar PR was merged which does everything this PR does already, just in a slightly different way regarding one scenario.

**Comment by formigarafa** [comment]
> Sorry for this huge delay. You're right, i could use some help with maintaining this project.
> 
> Back to subject: just merged very similar PR. Could you please rebase your working branch and resolve conflicts, so i could merge some of these changes.
> 
> @tim-s-ccs & @formigarafa if you interested in helping me with with maintaining this repo - please let me know

I wouldn't mind giving you a hand with that. I can try.

**Comment by Eric-Guo** [comment]
will testing this branch and feedback later.

**Pull request merged**
